config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  get "/todos", to: "todos#index", as: "todos"

  post "/todos", to: "todos#create"

  delete "/todos", to: "todos#destroy"

  delete "/todos/:task", to: "todos#delete_one", as: "todo"

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos= session[:todos] ||= []

  end
  def create
    session[:todos].push params[:task]
    redirect_to '/todos'
  end

  def destroy
    session[:todos].clear
    redirect_to todos_path
  end

  def delete_one
    session[:todos].delete(params[:task])
    redirect_to todos_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todosession</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
   <% @todos.each do |f| %>
   <li><%= f %>
  <%= button_to "X", todo_path(f), :method => :delete %>
   <% end %>
</li>
   <%= form_tag(todos_path) do %>
     <p>
      <%= label_tag(:task) %>
      <%= text_field_tag(:task, nil, autofocus: true) %>
    </p>
     <%= submit_tag "Add"%>
  <% end %>
<p>
  <%= link_to "Delete List", todos_path, method: "Delete" %>
  </p>